### ISSUE TITLE
How can I implement Full face gaze redirect, crop eyes and paste with poisson blending

### ISSUE THREAD

**Issue by todhm** [CVI-SZU/GazeFlow#5]
In readme file there is original image to redirected image example. 
how can I implement following examples?
Thank you

**Comment by ackness** [comment]
you can check the demo repo, https://github.com/ackness/GazeFlow_demo 
there is a full code to redirect eye images

**Comment by ackness** [comment]
For full face images, you need to crop the eye images from face image which are the same region if images are aligned. 
You can do eye redirection using the codes from demo repo, using the redirected eye images to replace the same region in origin full face image. Sometimes, if u redict the gaze angle to large, it may cause the edge of the eye image to be more obvious when replacing, so we are using poisson blending to improve this situation.

**Comment by todhm** [comment]
Okay great thanks
